export type ProcessId = "natural" | "washed" | "honey" | "anaerobic" | "other";
export type BrewId = "filter" | "espresso" | "omni" | "cupping";
export type RoastStyleId = "light" | "medium" | "dark";
export type FlavorId =
  | "fruity"
  | "lightSweet"
  | "deepSweet"
  | "bright"
  | "juicy"
  | "winey"
  | "floral"
  | "body"
  | "clean"
  | "balance";

export type Rec = "recommended" | "neutral" | "avoid";

export type BeanSize = "small" | "medium" | "large";
export type DensityClass = "soft" | "medium" | "hard";

export interface OriginInfo {
  id: string;
  name: string;
  regions: string;
  typicalProcess: ProcessId;
  typicalAltitude: number;
  density: DensityClass;
  shortCode?: string;
  notes?: string;
  cup?: string;
  suggestedVarietyId?: string;
}

export interface VarietyRoast {
  fcTemp: number;
  preheatW: number;
  dryingS: number;
  midS: number;
  developmentS: number;
  /** Offset from the official 14700 RPM hold (Kaffelogic Studio transform). */
  fanRpm: number;
}

export interface VarietyInfo {
  id: string;
  name: string;
  shortCode?: string;
  beanSize: BeanSize;
  density: DensityClass;
  flavorLean: FlavorId[];
  suggestedStyle: RoastStyleId;
  roast: VarietyRoast;
  notes?: string;
  cup?: string;
}

export interface FlavorInfo {
  id: FlavorId;
  name: string;
  icon: string;
  strategy: string[];
  why: string;
  expected: string[];
  tradeoffs: string[];
  warning: string;
  suggestedStyle: RoastStyleId;
}

export const ORIGINS: OriginInfo[] = [
  { id: "ethiopia", name: "Ethiopia", regions: "Yirgacheffe / Sidamo / Guji", typicalProcess: "natural", typicalAltitude: 2000, density: "hard", shortCode: "ETH", suggestedVarietyId: "heirloom" },
  { id: "kenya", name: "Kenya", regions: "Nyeri / Kirinyaga", typicalProcess: "washed", typicalAltitude: 1750, density: "hard", shortCode: "KEN", suggestedVarietyId: "sl28" },
  {
    id: "colombia",
    name: "Colombia",
    regions: "Andean departments",
    typicalProcess: "washed",
    typicalAltitude: 1700,
    density: "medium",
    shortCode: "COL",
    suggestedVarietyId: "caturra",
    notes: "Washed Arabica on three cordilleras. Pick a department below when you know the lot.",
    cup: "Clean, sweet, balanced",
  },
  {
    id: "colombia-huila",
    name: "Colombia — Huila",
    regions: "Pitalito / Acevedo / San Adolfo",
    typicalProcess: "washed",
    typicalAltitude: 1700,
    density: "hard",
    shortCode: "HUI",
    suggestedVarietyId: "caturra",
    notes: "Colombia’s main specialty volume. Volcanic valleys, 1,400–2,000 m, tank ferment 12–18 h. Honey lots are common on microlots.",
    cup: "Citrus, caramel, red fruit, winey sparkle",
  },
  {
    id: "colombia-narino",
    name: "Colombia — Nariño",
    regions: "Buesaco / La Unión / La Florida",
    typicalProcess: "washed",
    typicalAltitude: 2050,
    density: "hard",
    shortCode: "NAR",
    suggestedVarietyId: "caturra",
    notes: "Near the equator at 1,800–2,300 m. Hot days / ~10 °C nights slow ripening; very dense seed. Some honey / extended ferment.",
    cup: "Stone fruit, brown sugar, floral, high acidity",
  },
  {
    id: "colombia-cauca",
    name: "Colombia — Cauca",
    regions: "Inzá / Popayán plateau / Timbío",
    typicalProcess: "washed",
    typicalAltitude: 1850,
    density: "hard",
    shortCode: "CAU",
    suggestedVarietyId: "caturra",
    notes: "1,700–2,100 m plateau, cool nights, volcanic ash. Typically fully washed; clean terroir-forward cups.",
    cup: "Lime, cocoa, floral, tea-like body",
  },
  {
    id: "colombia-tolima",
    name: "Colombia — Tolima",
    regions: "Planadas / Herrera / Chaparral",
    typicalProcess: "washed",
    typicalAltitude: 1650,
    density: "medium",
    shortCode: "TOL",
    suggestedVarietyId: "caturra",
    notes: "Steep west-central slopes, 1,200–2,000 m. Emerging specialty; heavier than Huila next door.",
    cup: "Chocolate, green apple, nutty finish, more body",
  },
  {
    id: "colombia-sierra",
    name: "Colombia — Sierra Nevada",
    regions: "Santa Marta / Arhuaco / Kogi lands",
    typicalProcess: "washed",
    typicalAltitude: 1400,
    density: "soft",
    shortCode: "SNV",
    suggestedVarietyId: "typica",
    notes: "Caribbean isolated range, shade-grown 900–1,600 m, often organic. Softer seed than Andean lots — easier to tip if the front is too hot.",
    cup: "Low acidity, full body, chocolate, tropical",
  },
  {
    id: "colombia-antioquia",
    name: "Colombia — Antioquia / Eje Cafetero",
    regions: "Medellín / Quindío / Risaralda / Caldas",
    typicalProcess: "washed",
    typicalAltitude: 1550,
    density: "medium",
    shortCode: "ANT",
    suggestedVarietyId: "castillo",
    notes: "Classic Coffee Triangle, 1,200–1,800 m. The historical Colombian profile: consistent washed, year-round mitaca.",
    cup: "Caramel, citrus, balanced, mild body",
  },
  { id: "rwanda", name: "Rwanda", regions: "Nyamasheke / Huye", typicalProcess: "washed", typicalAltitude: 1800, density: "hard", shortCode: "RWA", suggestedVarietyId: "bourbon" },
  { id: "brazil", name: "Brazil", regions: "Cerrado / Minas", typicalProcess: "natural", typicalAltitude: 1100, density: "soft", shortCode: "BRA", suggestedVarietyId: "catuai" },
  { id: "guatemala", name: "Guatemala", regions: "Huehuetenango / Antigua", typicalProcess: "washed", typicalAltitude: 1600, density: "medium", shortCode: "GTM", suggestedVarietyId: "caturra" },
  { id: "costa-rica", name: "Costa Rica", regions: "Tarrazú / West Valley", typicalProcess: "honey", typicalAltitude: 1600, density: "medium", shortCode: "CRI", suggestedVarietyId: "caturra" },
  { id: "peru", name: "Peru", regions: "Cajamarca / Cusco", typicalProcess: "washed", typicalAltitude: 1800, density: "hard", shortCode: "PER", suggestedVarietyId: "typica" },
  { id: "indonesia", name: "Indonesia", regions: "Sumatra / Java", typicalProcess: "other", typicalAltitude: 1300, density: "soft", shortCode: "IDN", suggestedVarietyId: "typica" },
  { id: "yemen", name: "Yemen", regions: "Sana'a / Ibb", typicalProcess: "natural", typicalAltitude: 2000, density: "hard", shortCode: "YEM", suggestedVarietyId: "typica" },
];

/** Arabica cultivars that change density, seed size, and volatile flavor — so the roast must change too. */
export const VARIETIES: VarietyInfo[] = [
  {
    id: "unknown",
    name: "Unknown / mix",
    shortCode: "MIX",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["balance"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0, preheatW: 0, dryingS: 0, midS: 0, developmentS: 0, fanRpm: 0 },
    notes: "Use when the lot is a blend or the cultivar is not listed. No extra variety heat.",
    cup: "Follow origin and process",
  },
  {
    id: "typica",
    name: "Typica",
    shortCode: "TYP",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["clean", "bright"],
    suggestedStyle: "light",
    roast: { fcTemp: -0.3, preheatW: 2, dryingS: 0, midS: -2, developmentS: -4, fanRpm: 0 },
    notes: "The original cultivated Arabica. Clean, tea-like cups; keep development modest so it does not go nutty.",
    cup: "Clean, sweet, tea-like",
  },
  {
    id: "bourbon",
    name: "Bourbon",
    shortCode: "BRB",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["lightSweet", "deepSweet"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0.3, preheatW: 0, dryingS: 2, midS: 6, developmentS: 6, fanRpm: -50 },
    notes: "Sweeter and rounder than Typica. A slightly longer Maillard builds caramel without needing a dark drop.",
    cup: "Brown sugar, red fruit, more body than Typica",
  },
  {
    id: "yellow-bourbon",
    name: "Yellow Bourbon",
    shortCode: "YBR",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["lightSweet"],
    suggestedStyle: "light",
    roast: { fcTemp: 0.2, preheatW: 0, dryingS: 0, midS: 8, developmentS: 4, fanRpm: -50 },
    notes: "Brazil specialty staple. Extra mid-roast time for citric sweetness; do not stretch development into bake.",
    cup: "Citrus, honey, caramel",
  },
  {
    id: "pink-bourbon",
    name: "Pink Bourbon",
    shortCode: "PBR",
    beanSize: "medium",
    density: "hard",
    flavorLean: ["floral", "juicy"],
    suggestedStyle: "light",
    roast: { fcTemp: -1.5, preheatW: 8, dryingS: 2, midS: -8, developmentS: -12, fanRpm: 80 },
    notes: "Colombia microlot star. Volatile florals and tropical acidity — roast like Gesha: enough front energy, short development, avoid dark.",
    cup: "Jasmine, tropical, phosphoric sparkle",
  },
  {
    id: "caturra",
    name: "Caturra",
    shortCode: "CTR",
    beanSize: "small",
    density: "medium",
    flavorLean: ["bright", "clean"],
    suggestedStyle: "light",
    roast: { fcTemp: -0.5, preheatW: -2, dryingS: -3, midS: -4, developmentS: -4, fanRpm: -40 },
    notes: "Compact Bourbon mutation, common in Colombia and Central America. Slightly smaller seed — a touch faster through drying.",
    cup: "Bright, clean, citrus-sweet",
  },
  {
    id: "catuai",
    name: "Catuai",
    shortCode: "CTU",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["balance"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0, preheatW: 0, dryingS: 0, midS: 2, developmentS: 2, fanRpm: 0 },
    notes: "Mundo Novo × Caturra. Productive Brazil / Central America workhorse; treat as a balanced baseline.",
    cup: "Nutty sweet, mild citrus, even body",
  },
  {
    id: "castillo",
    name: "Castillo",
    shortCode: "CAS",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["body", "balance"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0.5, preheatW: 4, dryingS: 2, midS: 6, developmentS: 6, fanRpm: -80 },
    notes: "Colombia rust-resistant Catimor. More body, less sparkle than Caturra — a longer mid and a bit more development help the cup.",
    cup: "Chocolate, caramel, heavier body",
  },
  {
    id: "colombia-var",
    name: "Colombia (variety)",
    shortCode: "CVD",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["balance", "body"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0.3, preheatW: 4, dryingS: 2, midS: 4, developmentS: 4, fanRpm: -50 },
    notes: "FNC hybrid related to Castillo. Similar heat: a little more mid and development than a Caturra lot.",
    cup: "Sweet, balanced, moderate body",
  },
  {
    id: "gesha",
    name: "Gesha / Geisha",
    shortCode: "GSH",
    beanSize: "medium",
    density: "hard",
    flavorLean: ["floral", "bright"],
    suggestedStyle: "light",
    roast: { fcTemp: -2, preheatW: 10, dryingS: 2, midS: -10, developmentS: -16, fanRpm: 80 },
    notes: "Dense, high-grown, extremely volatile florals. Charge with energy so the seed catches, then get out after first crack. Dark roast erases the variety.",
    cup: "Jasmine, bergamot, tea, peach",
  },
  {
    id: "sl28",
    name: "SL28",
    shortCode: "S28",
    beanSize: "medium",
    density: "hard",
    flavorLean: ["bright", "juicy"],
    suggestedStyle: "light",
    roast: { fcTemp: -0.5, preheatW: 12, dryingS: 4, midS: -4, developmentS: -6, fanRpm: 80 },
    notes: "Kenya Scott Labs selection. Very dense; phosphoric / blackcurrant acids need a hot front and a restrained development.",
    cup: "Blackcurrant, grapefruit, tomato-savory sparkle",
  },
  {
    id: "sl34",
    name: "SL34",
    shortCode: "S34",
    beanSize: "medium",
    density: "hard",
    flavorLean: ["bright", "body"],
    suggestedStyle: "light",
    roast: { fcTemp: 0, preheatW: 10, dryingS: 4, midS: 2, developmentS: -2, fanRpm: 0 },
    notes: "Kenya companion to SL28. Same density, a little more body — keep acids, allow a touch more mid than SL28.",
    cup: "Citrus, brown sugar, fuller than SL28",
  },
  {
    id: "pacamara",
    name: "Pacamara",
    shortCode: "PCM",
    beanSize: "large",
    density: "medium",
    flavorLean: ["floral", "body"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0, preheatW: 16, dryingS: 12, midS: 4, developmentS: 2, fanRpm: 120 },
    notes: "Pacas × Maragogipe. Large seed takes longer to heat through — more preheat and drying, then a normal finish.",
    cup: "Floral, chocolate, wide body",
  },
  {
    id: "maragogipe",
    name: "Maragogipe",
    shortCode: "MRG",
    beanSize: "large",
    density: "soft",
    flavorLean: ["balance"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0, preheatW: 12, dryingS: 14, midS: 2, developmentS: 0, fanRpm: 150 },
    notes: "Elephant bean: huge, often softer than Pacamara. Extra dry time to cook the core; do not scorch the surface with an aggressive charge.",
    cup: "Mild, sweet, tea-like when not baked",
  },
  {
    id: "heirloom",
    name: "Ethiopian landrace",
    shortCode: "HEI",
    beanSize: "medium",
    density: "hard",
    flavorLean: ["floral", "fruity"],
    suggestedStyle: "light",
    roast: { fcTemp: -1, preheatW: 8, dryingS: 2, midS: -6, developmentS: -10, fanRpm: 50 },
    notes: "Mixed Ethiopian landraces. Treat as floral/fruit: dense enough for energy, short enough development to keep jasmine and berry.",
    cup: "Floral, bergamot, blueberry, tea",
  },
  {
    id: "wush-wush",
    name: "Wush Wush",
    shortCode: "WSH",
    beanSize: "medium",
    density: "hard",
    flavorLean: ["floral"],
    suggestedStyle: "light",
    roast: { fcTemp: -1.5, preheatW: 8, dryingS: 2, midS: -8, developmentS: -14, fanRpm: 80 },
    notes: "Ethiopian origin, now also Colombia. Gesha-adjacent florals — short development, light drop.",
    cup: "Rose, tropical, bergamot",
  },
  {
    id: "sidra",
    name: "Sidra",
    shortCode: "SDR",
    beanSize: "medium",
    density: "hard",
    flavorLean: ["floral", "fruity"],
    suggestedStyle: "light",
    roast: { fcTemp: -1.2, preheatW: 6, dryingS: 2, midS: -6, developmentS: -12, fanRpm: 80 },
    notes: "Bourbon-related Ecuador / Colombia specialty. Tropical-floral; keep Maillard compact and development short.",
    cup: "Tropical fruit, jasmine, candy",
  },
  {
    id: "tabi",
    name: "Tabi",
    shortCode: "TAB",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["clean"],
    suggestedStyle: "light",
    roast: { fcTemp: 0, preheatW: 2, dryingS: 0, midS: -2, developmentS: -2, fanRpm: 0 },
    notes: "Colombia rust-resistant Typica × Bourbon × Timor. Cleaner cup than Castillo; small deltas from a Caturra-like roast.",
    cup: "Clean, sweet, mild floral",
  },
  {
    id: "ruiru11",
    name: "Ruiru 11",
    shortCode: "RU11",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["body", "balance"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0.3, preheatW: 4, dryingS: 2, midS: 4, developmentS: 4, fanRpm: -50 },
    notes: "Kenya rust-resistant. Less sparkle than SL28; a little more mid and body development fills the cup.",
    cup: "Brown sugar, citrus, more body than SL28",
  },
  {
    id: "java",
    name: "Java",
    shortCode: "JAV",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["clean", "floral"],
    suggestedStyle: "light",
    roast: { fcTemp: -0.5, preheatW: 2, dryingS: 0, midS: -4, developmentS: -6, fanRpm: 40 },
    notes: "Clean, tea-like Typica lineage (Indonesia / Cameroon / Central America). Do not over-develop.",
    cup: "Tea, clean sweetness, light floral",
  },
  {
    id: "mundo-novo",
    name: "Mundo Novo",
    shortCode: "MNV",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["deepSweet", "body"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0.4, preheatW: 0, dryingS: 2, midS: 6, developmentS: 6, fanRpm: -80 },
    notes: "Brazil Typica × Bourbon. Chocolate and nut — give Maillard time; espresso-friendly.",
    cup: "Chocolate, nut, low sparkle",
  },
  {
    id: "chiroso",
    name: "Chiroso",
    shortCode: "CHR",
    beanSize: "medium",
    density: "hard",
    flavorLean: ["floral", "juicy"],
    suggestedStyle: "light",
    roast: { fcTemp: -1.5, preheatW: 8, dryingS: 2, midS: -8, developmentS: -12, fanRpm: 80 },
    notes: "Antioquia / Caicedo landrace look-alike (Ethiopian-like). Volatile florals and tropical acidity — roast like Gesha or Pink Bourbon: energy up front, short development, stay Light.",
    cup: "Jasmine, peach, tropical, bergamot",
  },
  {
    id: "ombligon",
    name: "Ombligón",
    shortCode: "OMB",
    beanSize: "medium",
    density: "hard",
    flavorLean: ["floral", "fruity"],
    suggestedStyle: "light",
    roast: { fcTemp: -1.4, preheatW: 8, dryingS: 2, midS: -7, developmentS: -12, fanRpm: 80 },
    notes: "Colombia navel bean. Often anaerobic / honey. Same Gesha-family heat: catch the dense seed, then get out so papaya and florals survive.",
    cup: "Papaya, floral, tropical candy",
  },
  {
    id: "papayo",
    name: "Papayo",
    shortCode: "PPY",
    beanSize: "medium",
    density: "hard",
    flavorLean: ["fruity", "floral"],
    suggestedStyle: "light",
    roast: { fcTemp: -1.3, preheatW: 6, dryingS: 2, midS: -6, developmentS: -12, fanRpm: 80 },
    notes: "Colombia specialty (papaya-shaped cherry). Tropical-floral; compact Maillard, short development.",
    cup: "Papaya, jasmine, candy",
  },
  {
    id: "sudan-rume",
    name: "Sudan Rume",
    shortCode: "SRU",
    beanSize: "medium",
    density: "hard",
    flavorLean: ["floral", "bright"],
    suggestedStyle: "light",
    roast: { fcTemp: -1.6, preheatW: 8, dryingS: 2, midS: -8, developmentS: -14, fanRpm: 80 },
    notes: "Ethiopian-Sudanese landrace, parent of many F1s. Gesha-adjacent florals and phosphoric sparkle — Light only.",
    cup: "Jasmine, citrus, tea, wild florals",
  },
  {
    id: "laurina",
    name: "Laurina",
    shortCode: "LAU",
    beanSize: "small",
    density: "medium",
    flavorLean: ["floral", "clean"],
    suggestedStyle: "light",
    roast: { fcTemp: -1, preheatW: 2, dryingS: -2, midS: -6, developmentS: -10, fanRpm: 40 },
    notes: "Bourbon Pointu. Small, lower caffeine, delicate cup. Do not charge like Gesha — the seed is smaller and easier to tip.",
    cup: "Tea, jasmine, lemon, light body",
  },
  {
    id: "red-bourbon",
    name: "Red Bourbon",
    shortCode: "RBR",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["lightSweet", "fruity"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0.3, preheatW: 0, dryingS: 2, midS: 6, developmentS: 6, fanRpm: -50 },
    notes: "Classic red-cherry Bourbon (Rwanda, El Salvador, Colombia). Same sweet mid-roast as Bourbon.",
    cup: "Red fruit, brown sugar, cocoa",
  },
  {
    id: "orange-bourbon",
    name: "Orange Bourbon",
    shortCode: "OBR",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["lightSweet", "juicy"],
    suggestedStyle: "light",
    roast: { fcTemp: 0.2, preheatW: 0, dryingS: 0, midS: 8, developmentS: 4, fanRpm: -50 },
    notes: "Bourbon colour mutation. Citrus-honey like Yellow Bourbon — extra mid, do not bake the finish.",
    cup: "Orange, honey, caramel",
  },
  {
    id: "pacas",
    name: "Pacas",
    shortCode: "PCS",
    beanSize: "small",
    density: "medium",
    flavorLean: ["lightSweet", "clean"],
    suggestedStyle: "light",
    roast: { fcTemp: -0.4, preheatW: -2, dryingS: -3, midS: -2, developmentS: -2, fanRpm: -40 },
    notes: "El Salvador Bourbon dwarf. Smaller seed than Bourbon — a touch faster through drying, keep it sweet.",
    cup: "Caramel, apple, clean sweetness",
  },
  {
    id: "villa-sarchi",
    name: "Villa Sarchi",
    shortCode: "VSA",
    beanSize: "small",
    density: "medium",
    flavorLean: ["bright", "clean"],
    suggestedStyle: "light",
    roast: { fcTemp: -0.5, preheatW: -2, dryingS: -3, midS: -4, developmentS: -4, fanRpm: -40 },
    notes: "Costa Rica Bourbon dwarf. Caturra-like compact seed; bright, clean, fast through the front.",
    cup: "Citrus, honey, clean",
  },
  {
    id: "tekisic",
    name: "Tekisic",
    shortCode: "TEK",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["lightSweet", "clean"],
    suggestedStyle: "light",
    roast: { fcTemp: 0.2, preheatW: 0, dryingS: 2, midS: 4, developmentS: 4, fanRpm: -40 },
    notes: "El Salvador improved Bourbon. Sweet and clean; a little more mid than Typica, less than a Brazil Bourbon.",
    cup: "Brown sugar, citrus, silk",
  },
  {
    id: "sl14",
    name: "SL14",
    shortCode: "S14",
    beanSize: "medium",
    density: "hard",
    flavorLean: ["bright", "clean"],
    suggestedStyle: "light",
    roast: { fcTemp: -0.3, preheatW: 10, dryingS: 4, midS: -2, developmentS: -4, fanRpm: 50 },
    notes: "Kenya Scott Labs Typica selection. Dense like SL28, a bit cleaner and less wild — hot front, restrained development.",
    cup: "Grapefruit, blackcurrant, tea",
  },
  {
    id: "batian",
    name: "Batian",
    shortCode: "BAT",
    beanSize: "medium",
    density: "hard",
    flavorLean: ["body", "bright"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0.2, preheatW: 8, dryingS: 4, midS: 4, developmentS: 2, fanRpm: 0 },
    notes: "Kenya rust-resistant (SL28/SL34 + Rume + Catimor). More body than SL28; keep some acid, allow a touch more mid.",
    cup: "Citrus, brown sugar, fuller Kenya",
  },
  {
    id: "k7",
    name: "K7",
    shortCode: "K7",
    beanSize: "medium",
    density: "hard",
    flavorLean: ["clean", "bright"],
    suggestedStyle: "light",
    roast: { fcTemp: -0.2, preheatW: 8, dryingS: 2, midS: -2, developmentS: -4, fanRpm: 40 },
    notes: "Kenya Typica-line. Dense, cleaner than SL28 — energy in the front, do not stretch development.",
    cup: "Citrus, tea, mild berry",
  },
  {
    id: "catimor",
    name: "Catimor",
    shortCode: "CTM",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["body", "balance"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0.5, preheatW: 4, dryingS: 2, midS: 6, developmentS: 6, fanRpm: -80 },
    notes: "Caturra × Timor Hybrid. Rust-resistant, more body than sparkle — same heat family as Castillo.",
    cup: "Chocolate, spice, heavier body",
  },
  {
    id: "sarchimor",
    name: "Sarchimor",
    shortCode: "SCM",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["body", "deepSweet"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0.5, preheatW: 4, dryingS: 2, midS: 6, developmentS: 6, fanRpm: -80 },
    notes: "Villa Sarchi × Timor. Productive rust-resistant; give Maillard time so it is chocolate, not grassy.",
    cup: "Cocoa, caramel, low sparkle",
  },
  {
    id: "marsellesa",
    name: "Marsellesa",
    shortCode: "MRS",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["clean", "balance"],
    suggestedStyle: "light",
    roast: { fcTemp: 0, preheatW: 2, dryingS: 0, midS: -2, developmentS: -2, fanRpm: 0 },
    notes: "Sarchimor selection (ECOM / Central America). Cleaner than a farm Catimor; small deltas from Caturra.",
    cup: "Clean, citrus-sweet, mild body",
  },
  {
    id: "parainema",
    name: "Parainema",
    shortCode: "PRN",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["balance", "body"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0.4, preheatW: 4, dryingS: 2, midS: 5, developmentS: 5, fanRpm: -60 },
    notes: "Honduras Sarchimor. Workhorse cup — more mid and development than Caturra, less sparkle.",
    cup: "Caramel, nut, moderate body",
  },
  {
    id: "centroamericano",
    name: "Centroamericano",
    shortCode: "H1",
    beanSize: "medium",
    density: "hard",
    flavorLean: ["floral", "bright"],
    suggestedStyle: "light",
    roast: { fcTemp: -1, preheatW: 6, dryingS: 2, midS: -6, developmentS: -10, fanRpm: 60 },
    notes: "F1 (Sarchimor × Rume). Can cup near Gesha when high-grown. Energy in the front, short development.",
    cup: "Floral, citrus, tropical, tea",
  },
  {
    id: "starmaya",
    name: "Starmaya",
    shortCode: "STY",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["floral", "clean"],
    suggestedStyle: "light",
    roast: { fcTemp: -0.8, preheatW: 4, dryingS: 0, midS: -4, developmentS: -8, fanRpm: 40 },
    notes: "F1 (Cirad). Floral-clean when well grown; keep development shorter than a Castillo.",
    cup: "Floral, citrus, clean sweetness",
  },
  {
    id: "yellow-catuai",
    name: "Yellow Catuai",
    shortCode: "YCT",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["lightSweet", "balance"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0, preheatW: 0, dryingS: 0, midS: 3, developmentS: 2, fanRpm: 0 },
    notes: "Yellow-fruit Catuai. Treat as the Catuai baseline with a little extra mid for honey-citrus.",
    cup: "Honey, citrus, nut",
  },
  {
    id: "acaia",
    name: "Acaia",
    shortCode: "ACA",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["deepSweet", "body"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0.4, preheatW: 0, dryingS: 2, midS: 6, developmentS: 6, fanRpm: -80 },
    notes: "Brazil Mundo Novo selection. Chocolate-nut — give Maillard time; espresso-friendly.",
    cup: "Chocolate, nut, low sparkle",
  },
  {
    id: "icatu",
    name: "Icatu",
    shortCode: "ICT",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["body", "deepSweet"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0.4, preheatW: 2, dryingS: 2, midS: 6, developmentS: 6, fanRpm: -80 },
    notes: "Brazil (Arabica × Robusta back-cross). More body than Catuai; same mid/development family as Mundo Novo.",
    cup: "Cocoa, spice, heavy body",
  },
  {
    id: "arara",
    name: "Arara",
    shortCode: "ARR",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["lightSweet", "body"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0.3, preheatW: 2, dryingS: 2, midS: 5, developmentS: 4, fanRpm: -50 },
    notes: "Brazil Obatã × Icatu. Yellow cherry, sweet and thick — a little more mid than Catuai.",
    cup: "Yellow fruit, caramel, body",
  },
  {
    id: "catucai",
    name: "Catucaí",
    shortCode: "CTC",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["balance", "body"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0.2, preheatW: 2, dryingS: 2, midS: 4, developmentS: 4, fanRpm: -40 },
    notes: "Icatu × Catuai. Brazil workhorse; fill the cup with mid and a bit of development.",
    cup: "Caramel, nut, even body",
  },
  {
    id: "maracaturra",
    name: "Maracaturra",
    shortCode: "MCT",
    beanSize: "large",
    density: "medium",
    flavorLean: ["floral", "body"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0, preheatW: 14, dryingS: 10, midS: 4, developmentS: 2, fanRpm: 100 },
    notes: "Maragogipe × Caturra. Large seed — extra preheat and drying so the core catches, then a normal finish.",
    cup: "Floral, citrus, wide body",
  },
  {
    id: "mokka",
    name: "Mokka",
    shortCode: "MOK",
    beanSize: "small",
    density: "hard",
    flavorLean: ["deepSweet", "winey"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0, preheatW: 6, dryingS: -2, midS: 4, developmentS: 2, fanRpm: 40 },
    notes: "Peaberry-small Yemen / Hawaii type. Dense but tiny — enough charge to catch, do not cook it like Pacamara.",
    cup: "Spice, dried fruit, cocoa",
  },
  {
    id: "jarc-74110",
    name: "74110",
    shortCode: "110",
    beanSize: "medium",
    density: "hard",
    flavorLean: ["floral", "fruity"],
    suggestedStyle: "light",
    roast: { fcTemp: -1, preheatW: 8, dryingS: 2, midS: -6, developmentS: -10, fanRpm: 50 },
    notes: "Ethiopian JARC selection (Gera). Treat as landrace: dense enough for energy, short development for florals and berry.",
    cup: "Jasmine, peach, bergamot",
  },
  {
    id: "jarc-74112",
    name: "74112",
    shortCode: "112",
    beanSize: "medium",
    density: "hard",
    flavorLean: ["floral", "bright"],
    suggestedStyle: "light",
    roast: { fcTemp: -1, preheatW: 8, dryingS: 2, midS: -6, developmentS: -10, fanRpm: 50 },
    notes: "Ethiopian JARC selection. Same heat as 74110 — Light, compact Maillard, get out after crack.",
    cup: "Floral, lemon, tea",
  },
  {
    id: "jarc-74158",
    name: "74158",
    shortCode: "158",
    beanSize: "medium",
    density: "hard",
    flavorLean: ["floral", "juicy"],
    suggestedStyle: "light",
    roast: { fcTemp: -1.1, preheatW: 8, dryingS: 2, midS: -7, developmentS: -11, fanRpm: 60 },
    notes: "Ethiopian JARC selection, common on Yirgacheffe bags. Volatile florals — roast with the landrace / Gesha family.",
    cup: "Bergamot, floral, juicy citrus",
  },
  {
    id: "jackson",
    name: "Jackson",
    shortCode: "JCK",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["lightSweet", "clean"],
    suggestedStyle: "light",
    roast: { fcTemp: 0.2, preheatW: 0, dryingS: 2, midS: 4, developmentS: 4, fanRpm: -40 },
    notes: "Bourbon-line (Rwanda / Burundi). Sweet and clean; a little more mid than Typica.",
    cup: "Brown sugar, red fruit, tea",
  },
  {
    id: "kent",
    name: "Kent",
    shortCode: "KNT",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["clean", "balance"],
    suggestedStyle: "medium",
    roast: { fcTemp: -0.2, preheatW: 2, dryingS: 0, midS: -2, developmentS: -2, fanRpm: 0 },
    notes: "India / Kenya Typica selection. Clean cup; keep development modest.",
    cup: "Tea, spice, clean sweetness",
  },
  {
    id: "blue-mountain",
    name: "Blue Mountain",
    shortCode: "BLM",
    beanSize: "large",
    density: "medium",
    flavorLean: ["clean", "lightSweet"],
    suggestedStyle: "light",
    roast: { fcTemp: -0.2, preheatW: 10, dryingS: 8, midS: -2, developmentS: -4, fanRpm: 60 },
    notes: "Jamaica Typica, often a large seed. Extra preheat and drying to cook the core; do not darken — the cup is mild and clean.",
    cup: "Clean, sweet, nut, low acid",
  },
  {
    id: "jarc-74165",
    name: "74165",
    shortCode: "165",
    beanSize: "medium",
    density: "hard",
    flavorLean: ["floral", "fruity"],
    suggestedStyle: "light",
    roast: { fcTemp: -1, preheatW: 8, dryingS: 2, midS: -6, developmentS: -10, fanRpm: 50 },
    notes: "Ethiopian JARC selection (Jimma). Same landrace heat as 74110 — Light, compact Maillard, short development.",
    cup: "Jasmine, stone fruit, tea",
  },
  {
    id: "jarc-74140",
    name: "74140",
    shortCode: "140",
    beanSize: "medium",
    density: "hard",
    flavorLean: ["floral", "bright"],
    suggestedStyle: "light",
    roast: { fcTemp: -1, preheatW: 8, dryingS: 2, midS: -6, developmentS: -10, fanRpm: 50 },
    notes: "Ethiopian JARC selection, common in Guji / Sidama washed lots. Landrace heat: energy up front, get out after crack.",
    cup: "Lemon, floral, black tea",
  },
  {
    id: "jarc-75227",
    name: "75227",
    shortCode: "227",
    beanSize: "medium",
    density: "hard",
    flavorLean: ["fruity", "floral"],
    suggestedStyle: "light",
    roast: { fcTemp: -1, preheatW: 8, dryingS: 2, midS: -6, developmentS: -10, fanRpm: 50 },
    notes: "Ethiopian JARC selection, a little rounder than 74110. Landrace heat — short development keeps the berry.",
    cup: "Berry, floral, round sweetness",
  },
  {
    id: "kurume",
    name: "Kurume",
    shortCode: "KUR",
    beanSize: "small",
    density: "hard",
    flavorLean: ["floral", "fruity"],
    suggestedStyle: "light",
    roast: { fcTemp: -1, preheatW: 6, dryingS: 0, midS: -6, developmentS: -10, fanRpm: 40 },
    notes: "Ethiopian local landrace (Sidama / Yirgacheffe), small seed. Landrace florals — a little less charge than 74110 so the small bean does not tip.",
    cup: "Blueberry, jasmine, lemon",
  },
  {
    id: "wolisho",
    name: "Wolisho",
    shortCode: "WOL",
    beanSize: "medium",
    density: "hard",
    flavorLean: ["floral", "fruity"],
    suggestedStyle: "light",
    roast: { fcTemp: -1, preheatW: 8, dryingS: 2, midS: -6, developmentS: -10, fanRpm: 50 },
    notes: "Ethiopian local landrace, bolder seed than Kurume. Landrace heat: energy up front, short development.",
    cup: "Stone fruit, floral, honey",
  },
  {
    id: "dega",
    name: "Dega",
    shortCode: "DEG",
    beanSize: "medium",
    density: "hard",
    flavorLean: ["floral", "lightSweet"],
    suggestedStyle: "light",
    roast: { fcTemp: -1, preheatW: 8, dryingS: 2, midS: -5, developmentS: -9, fanRpm: 50 },
    notes: "Ethiopian local landrace (Sidama / Guji). Floral-sweet; landrace heat with a touch more mid than Kurume.",
    cup: "Floral, honey, citrus",
  },
  {
    id: "abyssinia",
    name: "Abyssinia",
    shortCode: "ABY",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["floral", "fruity"],
    suggestedStyle: "light",
    roast: { fcTemp: -0.8, preheatW: 6, dryingS: 2, midS: -5, developmentS: -8, fanRpm: 40 },
    notes: "Ethiopian line planted in Java / Sumatra. Landrace-like florals, often wet-hulled — keep the front firm and development short.",
    cup: "Floral, spice, tropical fruit",
  },
  {
    id: "mejorado",
    name: "Typica Mejorado",
    shortCode: "MEJ",
    beanSize: "medium",
    density: "hard",
    flavorLean: ["floral", "bright"],
    suggestedStyle: "light",
    roast: { fcTemp: -1.4, preheatW: 8, dryingS: 2, midS: -8, developmentS: -12, fanRpm: 70 },
    notes: "Ecuador “improved Typica” — genetically an Ethiopian landrace, not Typica. Gesha-family heat: energy up front, short development.",
    cup: "Jasmine, lemon, stone fruit",
  },
  {
    id: "bourbon-aji",
    name: "Bourbon Ají",
    shortCode: "AJI",
    beanSize: "medium",
    density: "hard",
    flavorLean: ["fruity", "floral"],
    suggestedStyle: "light",
    roast: { fcTemp: -1.3, preheatW: 6, dryingS: 2, midS: -6, developmentS: -12, fanRpm: 80 },
    notes: "Colombia (Huila) specialty, Ethiopian-type despite the name. Sidra-family heat: compact Maillard, short development so the fruit stays.",
    cup: "Red fruit, floral, sweet-pepper aroma",
  },
  {
    id: "maragesha",
    name: "Maragesha",
    shortCode: "MGS",
    beanSize: "large",
    density: "medium",
    flavorLean: ["floral", "fruity"],
    suggestedStyle: "light",
    roast: { fcTemp: -1.2, preheatW: 14, dryingS: 8, midS: -6, developmentS: -12, fanRpm: 110 },
    notes: "Maragogipe × Gesha. Big seed with Gesha florals — extra preheat and drying to cook the core, then a Gesha-short development.",
    cup: "Jasmine, tropical fruit, wide body",
  },
  {
    id: "casiopea",
    name: "Casiopea",
    shortCode: "CSP",
    beanSize: "medium",
    density: "hard",
    flavorLean: ["floral", "bright"],
    suggestedStyle: "light",
    roast: { fcTemp: -0.9, preheatW: 6, dryingS: 2, midS: -5, developmentS: -9, fanRpm: 50 },
    notes: "F1 (Caturra × Ethiopian landrace). Floral like its Ethiopian parent — energy in the front, short development.",
    cup: "Floral, citrus, stone fruit",
  },
  {
    id: "striped-bourbon",
    name: "Striped Bourbon",
    shortCode: "SBR",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["fruity", "lightSweet"],
    suggestedStyle: "light",
    roast: { fcTemp: 0, preheatW: 0, dryingS: 2, midS: 4, developmentS: 2, fanRpm: -40 },
    notes: "Colombia “Bourbon Rayado” (striped cherry). Fruitier than Red Bourbon — Bourbon sweetness with a slightly shorter finish.",
    cup: "Red fruit, tamarind, cane sugar",
  },
  {
    id: "semperflorens",
    name: "Semperflorens",
    shortCode: "SMP",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["lightSweet", "balance"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0.2, preheatW: 0, dryingS: 2, midS: 4, developmentS: 4, fanRpm: -40 },
    notes: "Bourbon mutation that flowers year-round (El Salvador). Bourbon-family sweetness; a little more mid.",
    cup: "Brown sugar, stone fruit, round",
  },
  {
    id: "mibirizi",
    name: "Mibirizi",
    shortCode: "MIB",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["lightSweet", "fruity"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0.3, preheatW: 0, dryingS: 2, midS: 6, developmentS: 6, fanRpm: -50 },
    notes: "Old Bourbon-line selection (Rwanda / Burundi). Same sweet mid-roast as Bourbon.",
    cup: "Red fruit, cane sugar, tea",
  },
  {
    id: "venecia",
    name: "Venecia",
    shortCode: "VEN",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["bright", "lightSweet"],
    suggestedStyle: "light",
    roast: { fcTemp: 0, preheatW: 0, dryingS: 0, midS: 2, developmentS: 0, fanRpm: -20 },
    notes: "Costa Rica (ICAFE) Bourbon-type selection. Bourbon sweetness with a brighter finish — small deltas, a little extra mid.",
    cup: "Citrus, honey, silky",
  },
  {
    id: "yellow-caturra",
    name: "Yellow Caturra",
    shortCode: "YCA",
    beanSize: "small",
    density: "medium",
    flavorLean: ["bright", "lightSweet"],
    suggestedStyle: "light",
    roast: { fcTemp: -0.4, preheatW: -2, dryingS: -3, midS: -2, developmentS: -4, fanRpm: -40 },
    notes: "Yellow-fruit Caturra. Same compact seed as Caturra with a little more mid for honey.",
    cup: "Lemon, honey, clean",
  },
  {
    id: "villalobos",
    name: "Villalobos",
    shortCode: "VLB",
    beanSize: "small",
    density: "medium",
    flavorLean: ["bright", "clean"],
    suggestedStyle: "light",
    roast: { fcTemp: -0.5, preheatW: -2, dryingS: -3, midS: -4, developmentS: -4, fanRpm: -40 },
    notes: "Costa Rica Typica dwarf mutation. Compact seed — Caturra-like pacing, bright and clean.",
    cup: "Citrus, clean, light body",
  },
  {
    id: "san-ramon",
    name: "San Ramón",
    shortCode: "SRM",
    beanSize: "small",
    density: "medium",
    flavorLean: ["clean", "balance"],
    suggestedStyle: "medium",
    roast: { fcTemp: -0.3, preheatW: -2, dryingS: -2, midS: -2, developmentS: -2, fanRpm: -30 },
    notes: "Typica dwarf (Costa Rica / Hawaii). Small seed — a touch faster through drying; clean Typica cup.",
    cup: "Mild, sweet, clean",
  },
  {
    id: "pache",
    name: "Pache",
    shortCode: "PCH",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["clean", "balance"],
    suggestedStyle: "light",
    roast: { fcTemp: -0.3, preheatW: 2, dryingS: 0, midS: -2, developmentS: -4, fanRpm: 0 },
    notes: "Guatemala Typica dwarf (Pache Común / Colis). Typica heat — keep development modest.",
    cup: "Mild citrus, cocoa, clean",
  },
  {
    id: "mundo-maya",
    name: "Mundo Maya",
    shortCode: "MMY",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["clean", "balance"],
    suggestedStyle: "light",
    roast: { fcTemp: -0.2, preheatW: 2, dryingS: 0, midS: -2, developmentS: -2, fanRpm: 0 },
    notes: "F1 hybrid (Ecom / Cirad). Clean and even — small deltas from a Caturra-like roast.",
    cup: "Clean, citrus-sweet, round",
  },
  {
    id: "red-catuai",
    name: "Red Catuai",
    shortCode: "RCT",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["balance"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0, preheatW: 0, dryingS: 0, midS: 2, developmentS: 2, fanRpm: 0 },
    notes: "The common red-fruit Catuai. Same balanced baseline as Catuai.",
    cup: "Nutty sweet, red apple, even body",
  },
  {
    id: "topazio",
    name: "Topázio",
    shortCode: "TPZ",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["lightSweet", "balance"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0.1, preheatW: 0, dryingS: 0, midS: 3, developmentS: 3, fanRpm: -20 },
    notes: "Brazil Mundo Novo × Yellow Catuai. Catuai baseline with a little extra mid for yellow-fruit sweetness.",
    cup: "Yellow fruit, caramel, nut",
  },
  {
    id: "paraiso",
    name: "Paraíso",
    shortCode: "PRS",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["lightSweet", "balance"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0.2, preheatW: 2, dryingS: 2, midS: 4, developmentS: 3, fanRpm: -40 },
    notes: "Brazil Yellow Catuai × Timor (EPAMIG). Sweeter than a farm Catimor; a little more mid than Catuai.",
    cup: "Yellow fruit, honey, round",
  },
  {
    id: "garnica",
    name: "Garnica",
    shortCode: "GAR",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["balance", "body"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0.2, preheatW: 2, dryingS: 2, midS: 3, developmentS: 3, fanRpm: -30 },
    notes: "Mexico Mundo Novo × Yellow Caturra. Catuai-like workhorse — balanced baseline, a little extra mid.",
    cup: "Nut, caramel, mild citrus",
  },
  {
    id: "obata",
    name: "Obatã",
    shortCode: "OBT",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["body", "balance"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0.4, preheatW: 4, dryingS: 2, midS: 5, developmentS: 5, fanRpm: -60 },
    notes: "Brazil Sarchimor (IAC). Rust-resistant workhorse — give Maillard time so it reads chocolate, not grassy.",
    cup: "Cocoa, caramel, full body",
  },
  {
    id: "tupi",
    name: "Tupi",
    shortCode: "TUP",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["body", "deepSweet"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0.4, preheatW: 4, dryingS: 2, midS: 6, developmentS: 6, fanRpm: -70 },
    notes: "Brazil Sarchimor (Villa Sarchi × Timor). Body family: longer mid and a bit more development.",
    cup: "Chocolate, nut, low sparkle",
  },
  {
    id: "iapar-59",
    name: "IAPAR 59",
    shortCode: "IAP",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["body", "balance"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0.4, preheatW: 4, dryingS: 2, midS: 5, developmentS: 5, fanRpm: -60 },
    notes: "Brazil Sarchimor from Paraná. Same heat as Obatã — body family.",
    cup: "Caramel, cocoa, even body",
  },
  {
    id: "catigua",
    name: "Catiguá",
    shortCode: "CTG",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["body", "balance"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0.4, preheatW: 4, dryingS: 2, midS: 5, developmentS: 5, fanRpm: -60 },
    notes: "Brazil Catuai × Timor (EPAMIG). Rust-resistant; body family — give Maillard time.",
    cup: "Chocolate, caramel, sweet body",
  },
  {
    id: "anacafe-14",
    name: "Anacafé 14",
    shortCode: "A14",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["body", "lightSweet"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0.3, preheatW: 6, dryingS: 4, midS: 4, developmentS: 4, fanRpm: -20 },
    notes: "Guatemala Catimor × Pacamara. Bolder than Catuai with a body-family mid — a bit more preheat and drying, normal finish.",
    cup: "Red fruit, caramel, full body",
  },
  {
    id: "lempira",
    name: "Lempira",
    shortCode: "LEM",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["body", "balance"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0.5, preheatW: 4, dryingS: 2, midS: 6, developmentS: 6, fanRpm: -80 },
    notes: "Honduras Catimor (IHCAFE). Same heat family as Castillo — longer mid, more development.",
    cup: "Cocoa, spice, heavy body",
  },
  {
    id: "ihcafe-90",
    name: "IHCAFE 90",
    shortCode: "I90",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["body", "balance"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0.5, preheatW: 4, dryingS: 2, midS: 6, developmentS: 6, fanRpm: -80 },
    notes: "Honduras Catimor selection. Body family: give Maillard time, a little more development.",
    cup: "Chocolate, nut, heavier body",
  },
  {
    id: "costa-rica-95",
    name: "Costa Rica 95",
    shortCode: "C95",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["body", "balance"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0.5, preheatW: 4, dryingS: 2, midS: 6, developmentS: 6, fanRpm: -80 },
    notes: "Costa Rica Catimor (ICAFE). Rust-resistant, more body than sparkle — Castillo-like heat.",
    cup: "Cocoa, citrus, full body",
  },
  {
    id: "catisic",
    name: "Catisic",
    shortCode: "CTS",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["body", "lightSweet"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0.3, preheatW: 2, dryingS: 2, midS: 5, developmentS: 4, fanRpm: -50 },
    notes: "El Salvador Catimor selection. Sweeter than a plain Catimor; body family with a Bourbon-like mid.",
    cup: "Brown sugar, cocoa, body",
  },
  {
    id: "oro-azteca",
    name: "Oro Azteca",
    shortCode: "ORA",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["body", "balance"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0.5, preheatW: 4, dryingS: 2, midS: 6, developmentS: 6, fanRpm: -80 },
    notes: "Mexico Catimor (INIFAP). Castillo-like heat — longer mid and a bit more development.",
    cup: "Chocolate, nut, heavier body",
  },
  {
    id: "cenicafe-1",
    name: "Cenicafé 1",
    shortCode: "CN1",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["body", "balance"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0.4, preheatW: 4, dryingS: 2, midS: 5, developmentS: 5, fanRpm: -70 },
    notes: "Colombia FNC successor to Castillo. Same heat family — a longer mid and a bit more development.",
    cup: "Caramel, citrus, rounder body",
  },
  {
    id: "tim-tim",
    name: "Tim Tim",
    shortCode: "TIM",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["body", "deepSweet"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0.5, preheatW: 4, dryingS: 2, midS: 6, developmentS: 6, fanRpm: -80 },
    notes: "Timor Hybrid line common in Sumatra / Aceh. Body family — give Maillard time; usually wet-hulled.",
    cup: "Earthy cocoa, spice, heavy body",
  },
  {
    id: "ateng",
    name: "Ateng",
    shortCode: "ATG",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["body", "deepSweet"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0.5, preheatW: 4, dryingS: 2, midS: 6, developmentS: 6, fanRpm: -80 },
    notes: "Sumatra Catimor (Aceh / North Sumatra). Castillo-like heat; wet-hulled lots want an even front.",
    cup: "Cocoa, cedar, heavy body",
  },
  {
    id: "gayo-1",
    name: "Gayo 1",
    shortCode: "GY1",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["body", "balance"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0.4, preheatW: 4, dryingS: 2, midS: 5, developmentS: 5, fanRpm: -70 },
    notes: "Aceh Gayo selection (Timor line). Body family — longer mid, a little more development.",
    cup: "Chocolate, spice, round body",
  },
  {
    id: "sigarar-utang",
    name: "Sigarar Utang",
    shortCode: "SGU",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["body", "lightSweet"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0.4, preheatW: 4, dryingS: 2, midS: 5, developmentS: 4, fanRpm: -60 },
    notes: "North Sumatra Timor line (Lintong). Sweeter than Ateng; body family with a slightly shorter finish.",
    cup: "Brown sugar, spice, fruit, body",
  },
  {
    id: "s795",
    name: "S795",
    shortCode: "795",
    beanSize: "medium",
    density: "medium",
    flavorLean: ["body", "balance"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0.4, preheatW: 4, dryingS: 2, midS: 5, developmentS: 5, fanRpm: -60 },
    notes: "India Kent × S288 (Balehonnur), also planted in Indonesia. Rust-tolerant; body family — give Maillard time.",
    cup: "Chocolate, spice, mild acidity",
  },
  {
    id: "chandragiri",
    name: "Chandragiri",
    shortCode: "CHG",
    beanSize: "large",
    density: "medium",
    flavorLean: ["body", "balance"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0.4, preheatW: 10, dryingS: 8, midS: 5, developmentS: 4, fanRpm: 60 },
    notes: "India Sarchimor with a bold seed. Extra preheat and drying for the core, then a body-family mid.",
    cup: "Cocoa, nut, full body",
  },
  {
    id: "udaini",
    name: "Udaini",
    shortCode: "UDA",
    beanSize: "small",
    density: "hard",
    flavorLean: ["deepSweet", "winey"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0, preheatW: 6, dryingS: -2, midS: 4, developmentS: 2, fanRpm: 40 },
    notes: "Yemen landrace. Small dense seed — enough charge to catch, do not cook it like Pacamara.",
    cup: "Dried fruit, spice, cocoa",
  },
  {
    id: "tuffahi",
    name: "Tuffahi",
    shortCode: "TUF",
    beanSize: "small",
    density: "hard",
    flavorLean: ["fruity", "deepSweet"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0, preheatW: 6, dryingS: -2, midS: 3, developmentS: 0, fanRpm: 40 },
    notes: "Yemen landrace named for its apple-like cherry. Mokka heat: firm charge, modest development to keep the fruit.",
    cup: "Apple, dried fruit, spice",
  },
  {
    id: "dawairi",
    name: "Dawairi",
    shortCode: "DAW",
    beanSize: "small",
    density: "hard",
    flavorLean: ["deepSweet", "winey"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0, preheatW: 6, dryingS: -2, midS: 4, developmentS: 2, fanRpm: 40 },
    notes: "Yemen landrace (round leaf). Mokka-family heat — small dense seed, do not over-cook.",
    cup: "Raisin, cocoa, spice",
  },
  {
    id: "jaadi",
    name: "Jaadi",
    shortCode: "JAD",
    beanSize: "small",
    density: "hard",
    flavorLean: ["winey", "deepSweet"],
    suggestedStyle: "medium",
    roast: { fcTemp: 0, preheatW: 6, dryingS: -2, midS: 4, developmentS: 2, fanRpm: 40 },
    notes: "Yemen landrace (Haraz / Bani Matar). Mokka-family heat; keep some winey fruit.",
    cup: "Dried cherry, wine, spice",
  },
];

export const PROCESSES: { id: ProcessId; name: string }[] = [
  { id: "washed", name: "Washed" },
  { id: "natural", name: "Natural" },
  { id: "honey", name: "Honey" },
  { id: "anaerobic", name: "Anaerobic" },
  { id: "other", name: "Other / wet-hulled" },
];

export const BREWS: { id: BrewId; name: string }[] = [
  { id: "filter", name: "Filter" },
  { id: "espresso", name: "Espresso" },
  { id: "omni", name: "Omni" },
  { id: "cupping", name: "Cupping" },
];

/**
 * Nano `recommended_level` for each style. The machine scale is 0.1–5.9;
 * official guidance is 1.5–2.0 lighter, 2.5–3.5 medium, 4.0+ darker
 * (KL JP manual). Official Washed/Natural v1.1 ship at 1.4; Classic at 1.2.
 * Level is a stop on *this* curve’s `roast_levels` table, not a universal °C
 * or a DTR. On a fixed .kpro, raising level always raises DTR (Hilder);
 * Kaffe keeps DTR in-band by reshaping the post-crack slope (Alstrup).
 */
export const STYLES: { id: RoastStyleId; name: string; level: number }[] = [
  { id: "light", name: "Light", level: 1.6 },
  { id: "medium", name: "Medium", level: 3.2 },
  { id: "dark", name: "Dark", level: 4.6 },
];

export const FLAVORS: FlavorInfo[] = [
  {
    id: "fruity",
    name: "Fruity",
    icon: "🍓",
    strategy: ["High energy early", "Fast drying", "No extended Maillard", "Short development", "Lighter roast"],
    why: "Longer development drifts toward nutty, roasty and bitter notes; short development preserves fruity, sweet and acidic characters.",
    expected: ["Fruity", "Acidity", "Floral"],
    tradeoffs: ["Body", "Caramel / roasty"],
    warning: "Too short a development risks grassy or raw notes.",
    suggestedStyle: "light",
  },
  {
    id: "lightSweet",
    name: "Light Sweet",
    icon: "🍯",
    strategy: ["Moderate dry", "Keep Maillard compact", "Clean finish"],
    why: "A slightly longer Maillard than a fruit bomb, without pushing into caramelized darkness. Reads as cane, honey, or simple syrup — not brown sugar.",
    expected: ["Honey", "Cane sugar", "Clean"],
    tradeoffs: ["Heavy body"],
    warning: "Overstretching mid-roast mutes sparkle.",
    suggestedStyle: "light",
  },
  {
    id: "deepSweet",
    name: "Deep Sweet",
    icon: "🍬",
    strategy: ["Longer Maillard", "Later first crack", "More development"],
    why: "Slow browning builds melanoidins that taste like panela, molasses, date, or stewed fruit — low and round, not candy. Not caramel sauce and not milk chocolate.",
    expected: ["Panela", "Molasses", "Cooked fruit"],
    tradeoffs: ["Bright fruit"],
    warning: "Too much development turns sweet into baked.",
    suggestedStyle: "medium",
  },
  {
    id: "bright",
    name: "Bright Acidity",
    icon: "🍋",
    strategy: ["High energy front end", "Quick through drying", "Short development"],
    why: "Organic acids survive a fast, light roast; they collapse if you linger after crack.",
    expected: ["Citrus", "Sparkle"],
    tradeoffs: ["Body"],
    warning: "Soft beans can tip if the front is too aggressive.",
    suggestedStyle: "light",
  },
  {
    id: "juicy",
    name: "Juicy Acidity",
    icon: "🍑",
    strategy: ["Moderate dry", "Preserve acids", "Balanced mid"],
    why: "Juiciness wants acidity plus a little sweetness — not a race to drop.",
    expected: ["Stone fruit", "Acidity"],
    tradeoffs: ["Roasty"],
    warning: "Underdevelopment tastes thin rather than juicy.",
    suggestedStyle: "light",
  },
  {
    id: "winey",
    name: "Wine-like",
    icon: "🍇",
    strategy: ["Slower start", "Natural-process energy", "Keep some ferment character"],
    why: "Winey notes sit in natural and anaerobic coffees; a rushed dry flattens them.",
    expected: ["Winey", "Berry"],
    tradeoffs: ["Clean"],
    warning: "Easy to overdo into vinegar if development is too short on fermenty lots.",
    suggestedStyle: "light",
  },
  {
    id: "floral",
    name: "Floral",
    icon: "🌸",
    strategy: ["Gentle mid", "Early crack", "Very short development"],
    why: "Florals are volatile. Heat them late and they disappear.",
    expected: ["Floral", "Tea"],
    tradeoffs: ["Body"],
    warning: "Needs dense, high-grown washed or light naturals.",
    suggestedStyle: "light",
  },
  {
    id: "body",
    name: "Body",
    icon: "🫘",
    strategy: ["Longer Maillard", "Slightly lower late fan", "More development"],
    why: "Body builds as soluble browning compounds accumulate.",
    expected: ["Body", "Cocoa"],
    tradeoffs: ["Sparkle"],
    warning: "Darker than needed becomes ashy, not fuller.",
    suggestedStyle: "medium",
  },
  {
    id: "clean",
    name: "Clean",
    icon: "✨",
    strategy: ["Washed-style pacing", "Even energy", "No late stall"],
    why: "Clean cups come from even heat and avoiding fermenty linger.",
    expected: ["Clean", "Sweet"],
    tradeoffs: ["Winey"],
    warning: "Overly fast roasts can taste hollow instead of clean.",
    suggestedStyle: "light",
  },
  {
    id: "balance",
    name: "Balance",
    icon: "⚖️",
    strategy: ["Small deltas", "Classic 8–10 min", "Moderate DTR"],
    why: "Balance is the absence of a single loud phase.",
    expected: ["Sweet", "Acidity", "Body"],
    tradeoffs: ["Extreme fruit or dark roast"],
    warning: "Trying to please every slider at 100% cancels the idea.",
    suggestedStyle: "medium",
  },
];

export function flavorById(id: FlavorId): FlavorInfo {
  return FLAVORS.find((f) => f.id === id) ?? FLAVORS[0];
}

export function originById(id: string): OriginInfo {
  return ORIGINS.find((o) => o.id === id) ?? ORIGINS[0];
}

export function varietyById(id: string): VarietyInfo {
  return VARIETIES.find((v) => v.id === id) ?? VARIETIES[0];
}

const VOLATILE_VARIETIES = new Set([
  "gesha",
  "pink-bourbon",
  "heirloom",
  "wush-wush",
  "sidra",
  "chiroso",
  "ombligon",
  "papayo",
  "sudan-rume",
  "laurina",
  "centroamericano",
  "starmaya",
  "jarc-74110",
  "jarc-74112",
  "jarc-74158",
  "jarc-74165",
  "jarc-74140",
  "jarc-75227",
  "kurume",
  "wolisho",
  "dega",
  "abyssinia",
  "mejorado",
  "bourbon-aji",
  "maragesha",
  "casiopea",
]);
const BODY_VARIETIES = new Set([
  "castillo",
  "colombia-var",
  "ruiru11",
  "mundo-novo",
  "catimor",
  "sarchimor",
  "parainema",
  "icatu",
  "acaia",
  "arara",
  "catucai",
  "batian",
  "garnica",
  "obata",
  "tupi",
  "iapar-59",
  "catigua",
  "anacafe-14",
  "lempira",
  "ihcafe-90",
  "costa-rica-95",
  "catisic",
  "oro-azteca",
  "cenicafe-1",
  "tim-tim",
  "ateng",
  "gayo-1",
  "sigarar-utang",
  "s795",
  "chandragiri",
]);

export function isVolatileVariety(id: string): boolean {
  return VOLATILE_VARIETIES.has(id);
}

export function isBodyVariety(id: string): boolean {
  return BODY_VARIETIES.has(id);
}

export function varietyFamilyIds(): { volatile: string[]; body: string[] } {
  return { volatile: [...VOLATILE_VARIETIES], body: [...BODY_VARIETIES] };
}

/** Unknown first, then A–Z by the label the picker shows (Borbón Rojo sorts under B in Spanish). */
export function varietiesForSelect(
  labelOf: (v: VarietyInfo) => string = (v) => v.name,
  locale = "en",
): VarietyInfo[] {
  const unknown = VARIETIES.find((v) => v.id === "unknown");
  const rest = VARIETIES.filter((v) => v.id !== "unknown").sort((a, b) =>
    labelOf(a).localeCompare(labelOf(b), locale, { numeric: true, sensitivity: "base" }),
  );
  return unknown ? [unknown, ...rest] : rest;
}

const ALL_FLAVORS: FlavorId[] = [
  "fruity",
  "lightSweet",
  "deepSweet",
  "bright",
  "juicy",
  "winey",
  "floral",
  "body",
  "clean",
  "balance",
];
const LIGHT_NOTES: FlavorId[] = ["fruity", "floral", "bright", "juicy"];
const HEAVY_NOTES: FlavorId[] = ["deepSweet", "body"];

/** How strongly this bean + roast supports each goal. Negative = hard avoid. */
function flavorScore(
  flavor: FlavorId,
  process: ProcessId,
  style: RoastStyleId,
  origin: OriginInfo,
  variety?: VarietyInfo,
  density?: DensityClass,
): number {
  const named = variety && variety.id !== "unknown" ? variety : undefined;
  const volatile = named && VOLATILE_VARIETIES.has(named.id);
  const bodyFamily = named && BODY_VARIETIES.has(named.id);
  if (style === "dark" && LIGHT_NOTES.includes(flavor)) return -10;
  if (volatile && style === "light" && HEAVY_NOTES.includes(flavor)) return -10;
  if (bodyFamily && flavor === "floral" && style !== "light") return -10;
  if ((density ?? origin.density) === "soft" && flavor === "bright") return -10;
  if (origin.id === "colombia-sierra" && (flavor === "bright" || flavor === "floral")) return -10;

  let score = 0;
  if (style === "dark" && HEAVY_NOTES.includes(flavor)) score += 3;
  if (named?.flavorLean.includes(flavor)) score += 2.5;
  if (volatile && ["floral", "fruity", "bright"].includes(flavor)) score += 1.5;
  if (bodyFamily && ["body", "balance", "deepSweet"].includes(flavor)) score += 1.5;
  if (bodyFamily && flavor === "floral") score -= 1.5;
  if (process === "natural" && ["fruity", "winey", "juicy"].includes(flavor)) score += 1.5;
  if (process === "anaerobic" && ["winey", "fruity"].includes(flavor)) score += 1.5;
  if (process === "honey" && ["lightSweet", "juicy"].includes(flavor)) score += 1;
  if (process === "washed" && ["clean", "bright", "floral"].includes(flavor)) score += 1;
  if (process === "washed" && flavor === "winey") score -= 1;
  if (origin.id === "colombia-narino" && ["floral", "bright", "clean"].includes(flavor)) score += 1;
  if (origin.id === "colombia-huila" && ["juicy", "bright", "balance"].includes(flavor)) score += 1;
  if (origin.id === "colombia-sierra" && ["body", "deepSweet"].includes(flavor)) score += 1;
  if (origin.id === "colombia-tolima" && ["deepSweet", "body", "balance"].includes(flavor)) score += 1;
  if (style === "light" && [...LIGHT_NOTES, "lightSweet"].includes(flavor)) score += 0.75;
  if (style === "light" && HEAVY_NOTES.includes(flavor)) score -= 0.75;
  if (style === "medium" && ["balance", "lightSweet", "deepSweet", "body"].includes(flavor)) score += 0.5;
  return score;
}

/**
 * Recommended = the three strongest goals for this bean + roast (score ≥ 1.5), so the
 * picker points somewhere instead of lighting up every card. Avoid = the roast or the
 * seed works against that note.
 */
export function recommendFlavor(
  flavor: FlavorId,
  process: ProcessId,
  style: RoastStyleId,
  origin: OriginInfo,
  variety?: VarietyInfo,
  density?: DensityClass,
): Rec {
  const score = flavorScore(flavor, process, style, origin, variety, density);
  if (score <= -5) return "avoid";
  if (score < 1.5) return "neutral";
  const ranked = ALL_FLAVORS.map((id) => ({ id, s: flavorScore(id, process, style, origin, variety, density) }))
    .filter((x) => x.s >= 1.5)
    .sort((a, b) => b.s - a.s || ALL_FLAVORS.indexOf(a.id) - ALL_FLAVORS.indexOf(b.id));
  return ranked.slice(0, 3).some((x) => x.id === flavor) ? "recommended" : "neutral";
}
