import { createHash } from "node:crypto";
import { readdirSync, statSync } from "node:fs";
import { join, relative } from "node:path";
import type { Plugin } from "vite";

function publicFiles(dir: string, root = dir): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) out.push(...publicFiles(full, root));
    else out.push(relative(root, full).split("\\").join("/"));
  }
  return out;
}

/**
 * Writes `sw.js` at build time with every emitted file precached, so the installed app
 * works offline. Dev never registers it (the local coach API must stay live).
 */
export function pwaPlugin(): Plugin {
  let publicDir = "";
  return {
    name: "kaffe-pwa",
    apply: "build",
    configResolved(config) {
      publicDir = config.publicDir;
    },
    generateBundle(_options, bundle) {
      const files = [
        "./",
        ...Object.keys(bundle).map((f) => `./${f}`),
        ...publicFiles(publicDir).map((f) => `./${f}`),
      ].filter((f) => !f.endsWith(".map"));
      const version = createHash("sha256").update(files.join("\n")).digest("hex").slice(0, 12);
      const source = `/* Generated by vite/pwa.ts — do not edit. */
const CACHE = "kaffe-${version}";
const FONTS = "kaffe-fonts";
const PRECACHE = ${JSON.stringify([...new Set(files)])};
/* Hashed static files: match on URL alone. Module scripts carry an Origin header the precache request did not. */

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)));
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith("kaffe-") && k !== CACHE && k !== FONTS).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("message", (event) => {
  if (event.data === "skip-waiting") self.skipWaiting();
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.hostname === "fonts.googleapis.com" || url.hostname === "fonts.gstatic.com") {
    event.respondWith(
      caches.open(FONTS).then(async (cache) => {
        const hit = await cache.match(req, { ignoreVary: true });
        const fresh = fetch(req).then((res) => (cache.put(req, res.clone()), res)).catch(() => hit);
        return hit ?? fresh;
      }),
    );
    return;
  }
  if (url.origin !== self.location.origin) return;
  if (req.mode === "navigate") {
    event.respondWith(
      fetch(req)
        .then((res) => {
          const copy = res.clone();
          caches.open(CACHE).then((cache) => cache.put("./", copy));
          return res;
        })
        .catch(() => caches.match("./", { ignoreVary: true }).then((hit) => hit ?? caches.match("./index.html", { ignoreVary: true }))),
    );
    return;
  }
  event.respondWith(
    caches.match(req, { ignoreVary: true }).then(
      (hit) =>
        hit ??
        fetch(req).then((res) => {
          if (res.ok) {
            const copy = res.clone();
            caches.open(CACHE).then((cache) => cache.put(req, copy));
          }
          return res;
        }),
    ),
  );
});
`;
      this.emitFile({ type: "asset", fileName: "sw.js", source });
    },
  };
}
